version: "3.8"

services:
  wa-bot:
    image: moshtarek/whatsapp-evolution-bot:latest
    container_name: wa-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      # مجلد db مضمن في الصورة - لا حاجة لربطه كـ volume
      - ./images:/app/images
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
